export { default as Achievements } from './achievements'
export { default as Hero } from './hero'
export { default as Projects } from './projects'
export { default as Resume } from './resume'
export { default as Skills } from './skills'
